services:
  discord-bot:
    image: ${DOCKER_USERNAME}/epi-2030-bot:latest
    container_name: sapphire-bot
    restart: unless-stopped
    env_file: /opt/epi-bot/.env   
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
