name: Docker Build and Deploy to Debian 12

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Docker secrets are present
        run: |
          test -n "${{ secrets.DOCKER_USERNAME }}" || (echo "DOCKER_USERNAME is empty" && exit 1)
          test -n "${{ secrets.DOCKER_PASSWORD }}" || (echo "DOCKER_PASSWORD is empty" && exit 1)
          echo "Will push to: ${{ secrets.DOCKER_USERNAME }}/epi-2030-bot"

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/epi-2030-bot:latest
            ${{ secrets.DOCKER_USERNAME }}/epi-2030-bot:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy via SSH (docker run)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            docker pull docker.io/${{ secrets.DOCKER_USERNAME }}/epi-2030-bot:latest
            docker stop epi-2030-bot || true
            docker rm epi-2030-bot || true
            mkdir -p /opt/epi-bot
            if [ ! -f /opt/epi-bot/.env ]; then
              echo "DISCORD_TOKEN=REPLACE_ME" > /opt/epi-bot/.env
              echo "OPENAI_API_KEY=REPLACE_ME" >> /opt/epi-bot/.env
              echo "DATABASE_URL=REPLACE_ME" >> /opt/epi-bot/.env
              echo ">> /opt/epi-bot/.env créé (remplis les valeurs)."
            fi
            docker run -d \
              --name epi-2030-bot \
              --restart unless-stopped \
              --env-file /opt/epi-bot/.env \
              docker.io/${{ secrets.DOCKER_USERNAME }}/epi-2030-bot:latest
