name: PR Checks

on:
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check formatting
      run: |
        npm run format
        if [ -n "$(git diff --name-only)" ]; then
          echo "❌ Code is not properly formatted. Please run 'npm run format'"
          git diff --name-only
          exit 1
        else
          echo "✅ Code is properly formatted"
        fi
      
    - name: Build project
      run: npm run build