name: PR Checks

on:
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check formatting
      run: |
        npm run format
        if [ -n "$(git diff --name-only)" ]; then
          echo "FILES_CHANGED=$(git diff --name-only | tr '\n' ',')" >> $GITHUB_ENV
          echo "FORMATTING_NEEDED=true" >> $GITHUB_ENV
          git diff > formatting-changes.patch
        else
          echo "FORMATTING_NEEDED=false" >> $GITHUB_ENV
          echo "✅ Code is properly formatted"
        fi
        
    - name: Comment PR with formatting suggestions
      if: env.FORMATTING_NEEDED == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const patch = fs.readFileSync('formatting-changes.patch', 'utf8');
          const files = process.env.FILES_CHANGED.split(',').filter(f => f.length > 0);
          
          const body = `## ❌ Code formatting required
          
The following files need to be formatted:
${files.map(f => \`- \\\`${f}\\\`\`).join('\\n')}

Please run \\\`npm run format\\\` to fix the formatting issues.

<details>
<summary>📋 View formatting changes</summary>

\\\`\\\`\\\`diff
${patch}
\\\`\\\`\\\`
</details>`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          });
          
    - name: Fail if formatting needed
      if: env.FORMATTING_NEEDED == 'true'
      run: |
        echo "❌ Code formatting is required. Check the PR comment for details."
        exit 1
      
    - name: Build project
      run: npm run build